#!/usr/bin/env npx tsx
/**
 * Generate `skills/using-tribeunal/references/tools.md` from TOOL_DEFINITIONS.
 *
 * The skills describe *workflows* and deliberately never restate parameter
 * constraints — that catalogue is generated here so a new tool, a renamed
 * parameter or a changed annotation can never leave the skills stale.
 * `tests/skill-reference.test.ts` fails when the committed file drifts.
 *
 * Run: npm run gen:skills
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { TOOL_DEFINITIONS } from '../src/core/tools.js';

type ToolDef = (typeof TOOL_DEFINITIONS)[number];

export const REFERENCE_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../skills/using-tribeunal/references/tools.md',
);

/** Cell-safe: a literal pipe would split the markdown row. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').trim();
}

/**
 * First sentence of a tool description — the one-line "what it does".
 * Splits on a period followed by whitespace so decimals and "e.g." survive.
 */
function firstSentence(description: string): string {
  // The terminator must be followed by whitespace and something that starts a
  // new sentence — an uppercase letter or an opening bracket — or by the end of
  // the string. Splitting on any ". " truncated `tribeunal_post_comment` to
  // "Post a comment on a case — e.g." in the committed catalogue, and the drift
  // test could not catch it because it compares the generator against its own
  // output.
  const match = /^(.*?[.!?])(?:\s+(?=[A-Z(])|\s*$)/s.exec(description.trim());
  return (match ? match[1] : description.trim()).replace(/\s+/g, ' ');
}

/** `ro` / `destructive` / `open-world`, in that order; `—` when none apply. */
function flags(def: ToolDef): string {
  const a = def.annotations as {
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    openWorldHint?: boolean;
  };
  const on = [
    a?.readOnlyHint ? 'ro' : '',
    a?.destructiveHint ? 'destructive' : '',
    a?.openWorldHint ? 'open-world' : '',
  ].filter(Boolean);
  return on.length > 0 ? on.join(' ') : '—';
}

function required(def: ToolDef): string {
  const req = (def.inputSchema as { required?: readonly string[] }).required ?? [];
  return req.length > 0 ? req.join(', ') : '—';
}

/** Pure render — the test calls this and compares against the committed file. */
export function renderToolsReference(defs: readonly ToolDef[] = TOOL_DEFINITIONS): string {
  const rows = defs.map(
    (def) =>
      `| ${def.name} | ${cell(def.title)} | ${flags(def)} | ${cell(required(def))} | ${cell(firstSentence(def.description))} |`,
  );

  return [
    '# Tribeunal MCP tools',
    '',
    '<!-- Generated by `npm run gen:skills` from TOOL_DEFINITIONS in src/core/tools.ts. Do not edit by hand. -->',
    '',
    `${defs.length} tools, advertised identically on both transports — the stdio server (API key) and the`,
    'remote Cloudflare Worker at `mcp.tribeunal.com` (Auth0 OAuth). Your client prefixes them, so the same',
    'tool may appear as `mcp__tribeunal__tribeunal_get_case` or `Tribeunal:tribeunal_get_case`; the bare',
    'name below is the stable part.',
    '',
    'Flags: `ro` read-only · `destructive` not undoable · `open-world` reaches a system outside Tribeunal.',
    'Full parameter schemas come from the server itself — this table is the map, not the spec.',
    '',
    '| Tool | Title | Flags | Required | What it does |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// Written only when invoked as a script, so importing this module is side-effect free.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  writeFileSync(REFERENCE_PATH, renderToolsReference(), 'utf8');
  console.log(`wrote ${REFERENCE_PATH} (${TOOL_DEFINITIONS.length} tools)`);
}
